DROP TABLE  IF EXISTS INTERACTION_MANAGER_CANDIDATE_INT;
DROP TABLE  IF EXISTS MANAGER_CANDIDATE_INT;
DROP  TABLE IF EXISTS MANAGER;
DROP TABLE IF EXISTS CANDIDATE;
DROP TABLE IF EXISTS INTERACTION;
DROP SEQUENCE IF EXISTS global_seq;



CREATE SEQUENCE GLOBAL_SEQ   START WITH 100000;

CREATE TABLE MANAGER(
/*  id INT PRIMARY KEY AUTO_INCREMENT NOT NULL ,*/
    id  INT   DEFAULT  GLOBAL_SEQ.nextval PRIMARY KEY NOT NULL,
  fullname VARCHAR(255),
  email VARCHAR(255),
  CONSTRAINT manager_email_idx UNIQUE (email)
);


CREATE TABLE CANDIDATE(
  id  INT   DEFAULT  GLOBAL_SEQ.nextval PRIMARY KEY NOT NULL,
/*  id INT PRIMARY KEY AUTO_INCREMENT NOT NULL ,*/
  fullname VARCHAR(255),
  email VARCHAR(255),
  CONSTRAINT candidate_email_idx UNIQUE (email)
);


CREATE TABLE MANAGER_CANDIDATE_INT(
  manager_id INT NOT NULL,
  candidate_id INT NOT NULL,
  CONSTRAINT manager_id_fk FOREIGN KEY  (manager_id) REFERENCES manager (id),
  CONSTRAINT candidate_id_fk FOREIGN KEY  (candidate_id) REFERENCES candidate (id)
);

CREATE UNIQUE INDEX manager_candidate_idx ON MANAGER_CANDIDATE_INT (manager_id,candidate_id);

CREATE TABLE INTERACTION(
/*  id INT AUTO_INCREMENT NOT NULL ,*/
  id  INT   DEFAULT  GLOBAL_SEQ.nextval PRIMARY KEY NOT NULL,
  date_of_event TIMESTAMP,
  subject VARCHAR(255),
  comment VARCHAR(255)
);

CREATE TABLE INTERACTION_MANAGER_CANDIDATE_INT(
  manager_id INT NOT NULL,
  candidate_id INT NOT NULL,
  interaction_id INT NOT NULL,
  CONSTRAINT manager_id_interaction_fk FOREIGN KEY (manager_id) REFERENCES MANAGER (id),
  CONSTRAINT candidate_id_interaction_fk FOREIGN KEY (candidate_id) REFERENCES CANDIDATE (id),
  CONSTRAINT interaction_id_fk FOREIGN KEY (interaction_id) REFERENCES INTERACTION (id)
);

CREATE UNIQUE INDEX interaction_manager_candidate_idx ON INTERACTION_MANAGER_CANDIDATE_INT(manager_id,candidate_id,interaction_id);